### ISSUE TITLE
Dependency Issues in release 2.8.0

### ISSUE THREAD

**Issue by luhis** [Taritsyn/WebMarkupMin#104]
I am getting failing builds since updating the minifier to 2.8.0:
https://github.com/luhis/CodeGolf/pull/230

Error Message:
```error CS1705: Assembly 'WebMarkupMin.AspNetCore3' with identity 'WebMarkupMin.AspNetCore3, Version=2.8.0.0, Culture=neutral, PublicKeyToken=99472178d266584b' uses 'WebMarkupMin.Core, Version=2.7.1.0, Culture=neutral, PublicKeyToken=99472178d266584b' which has a higher version than referenced assembly 'WebMarkupMin.Core' with identity 'WebMarkupMin.Core, Version=2.7.0.0, Culture=neutral, PublicKeyToken=99472178d266584b'```

**Comment by Taritsyn** [comment]
Hello, Matt!

Yesterday before release, I tested update of packages and everything was fine.

Try updating the package manually.

**Comment by luhis** [comment]
I have the same problem when I try to update manually.  the package installs, but I cannot build.

**Comment by Taritsyn** [comment]
Try manually specifying the WebMarkupMin.Core package version:

```xml
<PackageReference Include="WebMarkupMin.Core" Version="2.7.1" />
```

**Comment by hootanht** [comment]
I Have This Issue : 
An error occurred while starting the application.
FileNotFoundException: Could not load file or assembly 'WebMarkupMin.Core, Version=2.7.1.0, Culture=neutral, PublicKeyToken=99472178d266584b'. The system cannot find the file specified.
WebMarkupMin.AspNetCore3.WebMarkupMinServiceCollectionExtensions.AddWebMarkupMin(IServiceCollection services, Action<WebMarkupMinOptions> configure)

FileNotFoundException: Could not load file or assembly 'WebMarkupMin.Core, Version=2.7.1.0, Culture=neutral, PublicKeyToken=99472178d266584b'. The system cannot find the file specified.

**Comment by Taritsyn** [comment]
This error is fixed in [version 2.8.1](https://github.com/Taritsyn/WebMarkupMin/releases/tag/v2.8.1).

**Comment by luhis** [comment]
@Taritsyn yeah, that has fixed it.  thanks

**Comment by azzusaiyed** [comment]
I have added Install-Package WebMarkupMin.AspNetCore3 -Version 2.8.1 for my dotnet core 3.01 project.
but unfortunately response of page comes blank.

**Comment by luhis** [comment]
@azzusaiyed I have the same problem, I raised another ticket for it

**Comment by azzusaiyed** [comment]
> @azzusaiyed I have the same problem, I raised another ticket for it

is it resolved ?

**Comment by Taritsyn** [comment]
> does is resolve ?

@luhis @azzusaiyed I will publish the package soon.

**Comment by Taritsyn** [comment]
@azzusaiyed Update the WebMarkupMin.AspNetCore3 package to version 2.8.2.

>  … for my dotnet core 3.01 project.

You will need to update your project to version .NET Core 3.1.

**Comment by azzusaiyed** [comment]
> @azzusaiyed Update the WebMarkupMin.AspNetCore3 package to version 2.8.2.
> 
> > … for my dotnet core 3.01 project.
> 
> You will need to update your project to version .NET Core 3.1.

Thanks it is working now.
